/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package strategicplangame;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Kauly
 */
public class BasicEnablers extends javax.swing.JFrame {

    ImageIcon diverse = new ImageIcon("Diversity.png");
    ImageIcon sustain = new ImageIcon("Sustainability.png");
    ImageIcon integrity = new ImageIcon("Intergity.png");
    ImageIcon account = new ImageIcon("Accountabilty.png");
    ImageIcon excel = new ImageIcon("Exellence.png");
    ImageIcon cardBack = new ImageIcon("playing-card-red.png");
    
    /**
     * Creates new form BasicEnablers
     */
    public BasicEnablers() {
        initComponents();
        setSize(1000,700);
        sustainPic.setIcon(cardBack);
        sustainPic.setText("");
        accountPic.setIcon(cardBack);
        accountPic.setText("");
        diversityPic.setIcon(cardBack);
        diversityPic.setText("");
        excellencePic.setIcon(cardBack);
        excellencePic.setText("");
        integrityPic.setIcon(cardBack);
        integrityPic.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        endGame = new javax.swing.JButton();
        previous = new javax.swing.JButton();
        accountPanel = new javax.swing.JPanel();
        accountPic = new javax.swing.JLabel();
        excelPanel = new javax.swing.JPanel();
        excellencePic = new javax.swing.JLabel();
        integrityPanel = new javax.swing.JPanel();
        integrityPic = new javax.swing.JLabel();
        diversePanel = new javax.swing.JPanel();
        diversityPic = new javax.swing.JLabel();
        accountBtn = new javax.swing.JButton();
        excelBtn = new javax.swing.JButton();
        integrityBtn = new javax.swing.JButton();
        sustainBtn = new javax.swing.JButton();
        diverseBtn = new javax.swing.JButton();
        sustainPanel = new javax.swing.JPanel();
        sustainPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VALUES");
        setMinimumSize(new java.awt.Dimension(800, 400));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        endGame.setText("END GAME");
        endGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endGameActionPerformed(evt);
            }
        });

        previous.setText("<-- Previous Level");
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });

        accountPanel.setBackground(new java.awt.Color(51, 51, 51));
        accountPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        accountPic.setText("accountPic");

        javax.swing.GroupLayout accountPanelLayout = new javax.swing.GroupLayout(accountPanel);
        accountPanel.setLayout(accountPanelLayout);
        accountPanelLayout.setHorizontalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountPic, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );
        accountPanelLayout.setVerticalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(accountPic)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        excelPanel.setBackground(new java.awt.Color(51, 51, 51));
        excelPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        excellencePic.setText("excellencePic");

        javax.swing.GroupLayout excelPanelLayout = new javax.swing.GroupLayout(excelPanel);
        excelPanel.setLayout(excelPanelLayout);
        excelPanelLayout.setHorizontalGroup(
            excelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(excelPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(excellencePic, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );
        excelPanelLayout.setVerticalGroup(
            excelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(excelPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(excellencePic)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        integrityPanel.setBackground(new java.awt.Color(51, 51, 51));
        integrityPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        integrityPic.setText("integrityPic");

        javax.swing.GroupLayout integrityPanelLayout = new javax.swing.GroupLayout(integrityPanel);
        integrityPanel.setLayout(integrityPanelLayout);
        integrityPanelLayout.setHorizontalGroup(
            integrityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(integrityPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(integrityPic, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        integrityPanelLayout.setVerticalGroup(
            integrityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(integrityPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(integrityPic)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        diversePanel.setBackground(new java.awt.Color(51, 51, 51));
        diversePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        diversityPic.setText("diversityPic");

        javax.swing.GroupLayout diversePanelLayout = new javax.swing.GroupLayout(diversePanel);
        diversePanel.setLayout(diversePanelLayout);
        diversePanelLayout.setHorizontalGroup(
            diversePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diversePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(diversityPic, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );
        diversePanelLayout.setVerticalGroup(
            diversePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diversePanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(diversityPic)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        accountBtn.setBackground(new java.awt.Color(204, 204, 204));
        accountBtn.setText("Accountability");
        accountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountBtnActionPerformed(evt);
            }
        });

        excelBtn.setBackground(new java.awt.Color(204, 204, 204));
        excelBtn.setText("Excellence");
        excelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excelBtnActionPerformed(evt);
            }
        });

        integrityBtn.setBackground(new java.awt.Color(204, 204, 204));
        integrityBtn.setText("Integrity");
        integrityBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                integrityBtnActionPerformed(evt);
            }
        });

        sustainBtn.setBackground(new java.awt.Color(204, 204, 204));
        sustainBtn.setText("Sustainability");
        sustainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sustainBtnActionPerformed(evt);
            }
        });

        diverseBtn.setBackground(new java.awt.Color(204, 204, 204));
        diverseBtn.setText("Diversity");
        diverseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diverseBtnActionPerformed(evt);
            }
        });

        sustainPanel.setBackground(new java.awt.Color(51, 51, 51));
        sustainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        sustainPic.setText("sustainPic");

        javax.swing.GroupLayout sustainPanelLayout = new javax.swing.GroupLayout(sustainPanel);
        sustainPanel.setLayout(sustainPanelLayout);
        sustainPanelLayout.setHorizontalGroup(
            sustainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sustainPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(sustainPic, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );
        sustainPanelLayout.setVerticalGroup(
            sustainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sustainPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(sustainPic)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(accountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)
                        .addComponent(excelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(accountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(excelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(integrityBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(integrityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sustainBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(previous)
                        .addGap(46, 46, 46)
                        .addComponent(sustainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(diversePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(endGame, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(diverseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(excelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(integrityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(excelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addComponent(accountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                    .addComponent(integrityBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sustainBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diverseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(endGame, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(218, 218, 218))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(previous, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(217, 217, 217))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(diversePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(sustainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void endGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endGameActionPerformed
        JOptionPane.showMessageDialog(null, "CONGRATULATIONS, YOU HAVE COMPLETED THE GAME. "
                + "\nLogin again to play again from the beginning");
        
        new Welcome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_endGameActionPerformed

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
        new Strategic_Direction().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_previousActionPerformed

    private void accountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountBtnActionPerformed
        accountPic.setIcon(account);
        accountPanel.setBackground(Color.green);
    }//GEN-LAST:event_accountBtnActionPerformed

    private void excelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excelBtnActionPerformed
        excellencePic.setIcon(excel);
        excelPanel.setBackground(Color.green);
    }//GEN-LAST:event_excelBtnActionPerformed

    private void integrityBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_integrityBtnActionPerformed
        integrityPic.setIcon(integrity);
        integrityPanel.setBackground(Color.green);
    }//GEN-LAST:event_integrityBtnActionPerformed

    private void sustainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sustainBtnActionPerformed
        sustainPic.setIcon(sustain);
        sustainPanel.setBackground(Color.green);
    }//GEN-LAST:event_sustainBtnActionPerformed

    private void diverseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diverseBtnActionPerformed
        diversityPic.setIcon(diverse);
        diversePanel.setBackground(Color.green);
    }//GEN-LAST:event_diverseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasicEnablers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasicEnablers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasicEnablers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasicEnablers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BasicEnablers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountBtn;
    private javax.swing.JPanel accountPanel;
    private javax.swing.JLabel accountPic;
    private javax.swing.JButton diverseBtn;
    private javax.swing.JPanel diversePanel;
    private javax.swing.JLabel diversityPic;
    private javax.swing.JButton endGame;
    private javax.swing.JButton excelBtn;
    private javax.swing.JPanel excelPanel;
    private javax.swing.JLabel excellencePic;
    private javax.swing.JButton integrityBtn;
    private javax.swing.JPanel integrityPanel;
    private javax.swing.JLabel integrityPic;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton previous;
    private javax.swing.JButton sustainBtn;
    private javax.swing.JPanel sustainPanel;
    private javax.swing.JLabel sustainPic;
    // End of variables declaration//GEN-END:variables
}
